### ISSUE TITLE
libappimageupdate.so: No such file or directory

### ISSUE THREAD

**Issue by hrantzsch** [TheAssassin/AppImageLauncher#119]
Trying to run AppImageLauncher, or any AppImage, gives me `AppImageLauncher: error while loading shared libraries: libappimageupdate.so: cannot open shared object file: No such file or directory`.

I'm on Arch and I installed AppImageLauncher from the AUR package. So it could be an issue with the package as well.

Adjusting LD_LIBRARY_PATH and similar workarounds like in #51 fix the problem as expected.

Thank you!

**Comment by TheAssassin** [comment]
The AUR stuff tends to be outdated. Will try to have a look. CC @NuLogicSystems.

**Comment by glitsj16** [comment]
@hrantzsch You could add a file (e.g. appimagelauncher.conf) to /etc/ld.so.conf.d containing one line: `/usr/lib/appimagelauncher` and run `sudo ldconfig` once. After doing so, you should no longer need to rely on any LD_LIBRARY_PATH workaround. I'm on Arch too and this works very well. It would be nice if you could confirm that this works as expected, in which case whoever is maintaining the AUR PKGBUILD could add a file like that by default. Just a thought :-)

**Comment by glitsj16** [comment]
@TheAssassin Keeping the bundled libraries in a separate location is exactly what's achieved by adding such a file to /etc/ld.so.conf.d. Running ldconfig avoids having unresolved symbols and/or unfound libraries. Arch's package manager pacman always runs it after any install. Or am I misunderstanding something here?

Regarding the AUR package, I suppose you could ask the maintainer to remove it. There's a dedicated thread for AUR stuff at https://bbs.archlinux.org/viewforum.php?id=38. I never did succeed in getting AppImageLauncher compiled using https://aur.archlinux.org/packages/appimagelauncher-git/.

**Comment by TheAssassin** [comment]
`ldconfig` will put such libraries into a form of "globally accessible directory", i.e., all applications run through the linker will have access to the libraries. That's not intended.

Actually, we use runpaths (rpaths) to make sure libraries can be found. This seems to have broke on Arch/AUR after pushinghttps://github.com/TheAssassin/AppImageLauncher/commit/7151d7af518159a77cd357aa4c9e3ef66c3b1e79.

**Comment by glitsj16** [comment]
@TheAssassin Had another look and all that's needed for Arch Linux is to `place all *.so files into /usr/lib`. When that's the case, everything falls into place as expected and both the ugly ldconfig hack and LD_LIBRARY_PATH workaround can be avoided. The current AUR PKGBUILD for appimagelauncher-git doesn't do this, that much is already established. What's new or unreported is that a manual `cmake`, `make` and `make install` routine doesn't produce the desired outcome on Arch Linux.

Steps to reproduce:

* install depends
    $ sudo pacman -S binutils boost-libs desktop-file-utils gtk-update-icon-cache inotify-tools libappimage libbsd shared-mime-info qt5-base

* install makedepends:
    $ sudo pacman -S boost cmake git qt5-tools

$ git clone https://github.com/TheAssassin/AppImageLauncher.git
...

$ cd AppImageLauncher
$ git submodule update --init --recursive
...

$ cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib  -DUSE_CCACHE=ON -DUSE_SYSTEM_LIBAPPIMAGE=ON 2>&1 | tee debug.cmake.log
...
debug.cmake.log: https://ptpb.pw/3qw0.log

$ make 2>&1 | tee debug.make.log
...
debug.make.log: https://ptpb.pw/Tk_Y.log

$ mkdir -p ./zzz
$ make DESTDIR=zzz install 2>&1 | tee debug.make.install.log
...
debug.make.install.log: https://ptpb.pw/Db26.log

Neither `./lib/AppImageUpdate/src/libappimageupdate.so` nor `./lib/AppImageUpdate/src/qt-ui/libappimageupdate-qt.so` get installed on Arch. They are built properly as far as I can deduce from the logs. Hope this helps to throw some light on what's missing/needs fixing.

**Comment by TheAssassin** [comment]
@glitsj16 I will try to build in a Manjaro VM I have later. Thanks for looking into it, I know what to look out for now.

**Comment by TheAssassin** [comment]
Seems the CMake version on Manjaro worked a bit differently. I've reworked the rpath handling, and it should be fixed now. Can you please

**Comment by hrantzsch** [comment]
I could only try on Manjaro now. The package appimagelauncher in the community repos works great, the package appimagelauncher-git in the AUR still cannot load libappimageupdate.so.

**Comment by glitsj16** [comment]
Really appreciate you're efforts looking into this. No changes though. Both `libappimageupdate.so` and `libappimageupdate-qt.so` are still missing from the make install DESTDIR. The only noticeable change is that now there's /usr/lib/appimagelauncher/appimagelauncher instead of just /usr/lib/appimagelauncher. Which contains `remove` and `update` files.
debug.make.install.log: https://ptpb.pw/6ARg.log

**Comment by TheAssassin** [comment]
@glitsj16 I've built it in my Manjaro VM and it worked fine. Both libraries were installed just fine. This is strange.

@hrantzsch does `/usr/lib/appimagelauncher` contain some `.so` files? If yes, which ones?

**Comment by TheAssassin** [comment]
Ah crap, seems to have become worse. All that stuff should end up in `lib/appimagelauncher`.

I'll have to boot a more recent Manjaro VM later.

**Comment by TheAssassin** [comment]
After lots of refactoring and then pointless debugging I found the issue: We just have to call CMake twice in the AUR PKGBUILD script. I fixed a lot of inconsistencies in the code base in the process, which is always good, and this issue is resolved now. I discovered a new issue on Manjaro XFCE, though, which I'm going to fix soon, too.

Please test and reopen if the issue persists.

**Comment by TheAssassin** [comment]
The issues should now all be fixed.

**Comment by glitsj16** [comment]
@TheAssassin Confirming the issues are fixed. A big thank you for taking the time and efforts to resolve this!

On a side-note, two remarks related to the current AUR PKGBUILD status.
* If you so desire, a request for removal could be made by the current submitter/maintainer. There's a few places one can do this. Via [IRC channels](https://wiki.archlinux.org/index.php/Arch_IRC_channels) 'main Arch Linux support' or 'AUR general discussion'. Another option is to ask on the [AUR related subforum](https://bbs.archlinux.org/viewforum.php?id=38). And finally, IMHO the most suitable place, via the [public mailing list for AUR package deletion/merge/orphan requests](https://lists.archlinux.org/listinfo/aur-requests).
* The current PKGBUILD is not in good shape. Issues in the [description, depends and makedepends arrays](https://wiki.archlinux.org/index.php/PKGBUILD), plus it doesn't make use of the [libappimage](https://www.archlinux.org/packages/extra/x86_64/libappimage/) package available in the official repos.

The first issue I cannot be of any real help. But - if you're so inclined - maybe I could help with the second one. To avoid repetitive issues being filed here or on the AUR by people who don't even bother to read the warnings you've so kindly put in the code, I'm willing to post a short comment on the present, good-looking state of upstream code. This could include a link to a [reworked PKGBUILD like this](https://ptpb.pw/lK23). Needless to say this awaits your approval.

Thanks again for your work, regards!

**Comment by NuLogicSystems** [comment]
There was a very good reason for not using the libappimage package on the -git continuous AUR build.
1: The code required a specific release of libappimage pulled in as a sub module.
2: It didn't exist when we originally created this pkgbuild

Philip from Manjaro maintains this package now for the Manjaro community repository. There was no need for me to continue working on this. With that said, a new AUR entry should be created to build the released version rather than the continuous tag, or master branch of the git code, this would achieve a more stable build, and would require way less maintenance of the PKGBUILD, etc.

**Comment by glitsj16** [comment]
@NuLogicSystems Hello. Let me start by thanking you for offering appimagelauncher-git in the AUR. I do understand your reasoning related to `libappimage`. I did try the Manjaro package, not with much succes. As an Arch Linux user with zero Manjaro experience I did feel a bit outside my comfort-zone doing so. Hence I tried to prep a PKGBUILD as I'm used to, instead of integrating a Manjaro repository into Arch's /etc/pacman.conf. If I was using Ubuntu I wouldn't install a Debian package neither, for the same reasons, nothing more, nothing less.

Your comment on the AUR page is crystal clear, no problems whatsoever with those. I wanted to test the latest AppImageLauncher code from git extensively, stumbled on some issues and tried to inform on/help fix those with the limited knowledge I have, especially of CMake, which happened to prove to be the main obstacle during this endeavour.

Thanks to TheAssassin's efforts these issues are now solved :-). I could have dropped things at this point, yet I felt the urge to somehow contribute to the AUR page for this handy app. Would you, as submitter/co-maintainer be willing to make another edit of the PKGBUILD for this git version, including depending on libappimage now? Again, I am not seeking credits or the like, hence I wouldn't mind you (or anyone else for that matter) using anything from the PKGBUILD I refered to above that is deemed useful and correct. For the record, I made a mistake in that linked PKGBUILD. In the depends array `inotify-tools` should be replaced by `libnotify`: https://ptpb.pw/MTX0.

As you've noticed, I avoided the topic of a `release` PKGBUILD for this app missing from AUR. I have to deal with a family member's medical issues in the foreseeable future, and that's taking up more time and energy than I expected. I would have offered putting one together and maintaining it if the homefront situation was less stressy. Whatever you decide to do with the current AUR package, you have my sincere appreciation.

Regards

**Comment by NuLogicSystems** [comment]
Well, I'm going to leave merging anything from your linked PKGBUILD for TheAssassin to look at for now. He would know better than I, if using the libappimage package by Antonio would be OK, or if the code requires it as a submodule. And for the reason that I have not been able to make it into the office for the last two weeks as I've been fighting off the flu. Hopefully I can get rid of this bug soon and get back to work myself. This is also something I would rather not have one of my employees working on either, they have enough networking and system repair work to do. Especially with me currently out of commission.

**Comment by TheAssassin** [comment]
@glitsj16 would you like to take over maintenance of the AUR recipe? I'm not interested in maintaining this stuff, since I don't use nor like Arch.

We should be able to use the system libappimage version just fine.
